POST http://localhost/api/v1/users
Content-Type: application/json

{
  "firstName": "dan",
  "lastName": "100",
  "email":"dan@mail.com",
  "password": "Secret123!"
}


POST http://localhost/api/v1/users/create-many
Content-Type: application/json

{
"users": 
   [
     {
      "firstName": "chris",
      "email": "chris@mail.com",
      "lastName": "100",
      "password": "Secret123!"
    },
    {
      "firstName": "dan",
      "email": "dan@mail.com",
      "lastName": "100",
      "password": "Secret123!"
    },
    {
      "firstName": "iza",
      "email": "iza@mail.com",
      "lastName": "100",
      "password": "Secret123!"
    }
   ]
}

