POST http://localhost:3000/api/v1/posts
Content-Type: application/json


{
  "title": "test-7",
  "postType": "post",
  "slug": "test-7",
  "status": "scheduled",
  "content": "This is the content of the post.",
  "schema": "{\"layout\":\"default\",\"seo\":{\"title\":\"My Third Post\"}}",
  "featuredImageUrl": "https://example.com/image.jpg",
  "tags": [],
  "publishOn": "2025-11-30T10:00:00Z",

  "metaOptions": {
      "metaValue": "{\"sidebarEnabled\": false, \"footerActive\" : false}"
    },
  "authorId": 1
}

