PATCH http://localhost/api/v1/posts
Content-Type: application/json

{
  "id": 27,
  "title": "This is a test fo patch request for id 27",
  "postType": "post",
  "slug": "my-first-post-for-id-27",
  "status": "published",
  "content": "This is the content of the post.",
  "schema": "{\"layout\":\"default\",\"seo\":{\"title\":\"My First Post\"}}",
  "featuredImageUrl": "https://example.com/image.jpg",
  "publishOn": "2025-11-30T10:00:00Z",
  "metaOptions": [
  
  ],
  "tags": [1,2,3,4]

}

